INSERT INTO avatar
	(avatar_url)
VALUES
	('/src/asset/avatars/avatar_default.png');

INSERT INTO rule
	(rule_name)
VALUES
    ('Capture d\'écran'),
    ('Retouches'),
    ('Appareil photo'),
    ('Faire poser une personne'),
    ('Smartphone'),
    ('Ajout de texte'),
    ('Ajout d\'illustration');

INSERT INTO status
    (status_name)
VALUES
    ('post'),
    ('vote'),
    ('completed');

INSERT INTO theme
    (theme_name)
VALUES
    ('Encore un matin'),
    ('Vue d’en haut'),
    ('En-dessous'),
    ('Technologie'),
    ('Ras du sol'),
    ('Reflets'),
    ('Ombre'),
    ('Un objet'),
    ('Drapeaux'),
    ('Sublimer un déchets'),
    ('Amour'),
    ('Pays'),
    ('Vert'),
    ('Photo culinaire'),
    ('Bleu'),
    ('Rouge'),
    ('Jaune'),
    ('Noir'),
    ('Blanc'),
    ('Miroir'),
    ('Courbes'),
    ('Avant – après'),
    ('Symétrie'),
    ('Lignes'),
    ('Flower Power'),
    ('Petit bonheur'),
    ('Joie'),
    ('Peur'),
    ('Noir & Blanc'),
    ('Souvenir d’enfance'),
    ('Animal'),
    ('Dans mon sac'),
    ('Lecture'),
    ('Ecriture'),
    ('Coloré'),
    ('Escaliers'),
    ('Contre-jour'),
    ('Tic-Tac'),
    ('Horizon'),
    ('Caché'),
    ('Pont'),
    ('Ras du sol Reflets'),
    ('Vue du dessus'),
    ('Sur la tête'),
    ('C’est dans l’air'),
    ('Microcosmos'),
    ('Regard'),
    ('Yeux'),
    ('Mains'),
    ('Couteau'),
    ('Machine'),
    ('Pièce'),
    ('Clé'),
    ('Bijou'),
    ('Impossible'),
    ('Balle & ballon'),
    ('Rythme'),
    ('Sport'),
    ('Décalé'),
    ('Fourchette'),
    ('Fentes'),
    ('Œuf'),
    ('Pierre et rocher'),
    ('Nuit'),
    ('Métal'),
    ('Rue'),
    ('Répétition'),
    ('Feu'),
    ('Route'),
    ('Empilement'),
    ('Parallèle'),
    ('Perpendiculaire'),
    ('Opposés'),
    ('Champignon'),
    ('Argent'),
    ('Chaussure'),
    ('Silhouette'),
    ('Musique'),
    ('Multitude'),
    ('Mouvement'),
    ('Coucher de soleil'),
    ('Au bord de l’eau'),
    ('Petit trésor'),
    ('Splash !'),
    ('Surprise !'),
    ('Magie'),
    ('L’eau'),
    ('Porte'),
    ('A moitié'),
    ('Goutte'),
    ('Ne pas déranger'),
    ('Vieux'),
    ('Sale'),
    ('Illusion'),
    ('Propre'),
    ('Perspective'),
    ('De l’autre côté'),
    ('Fenêtre'),
    ('Liberté'),
    ('Lumière'),
    ('Temps'),
    ('Détail'),
    ('Solitude'),
    ('Absurde'),
    ('Vitesse'),
    ('Vagues'),
    ('Autoportrait'),
    ('Jeune'),
    ('Abandonné'),
    ('Froid'),
    ('Chaud'),
    ('Architecture'),
    ('Nature'),
    ('Texture'),
    ('Sombre'),
    ('Ailleurs'),
    ('Coupé'),
    ('Cinéma'),
    ('Guerre'),
    ('Horreur'),
    ('Paysage'),
    ('Gros plan'),
    ('Trio'),
    ('Nostalgie'),
    ('A la queue leu-leu'),
    ('Perché'),
    ('Rond(s)'),
    ('Carré(s)'),
    ('Ça flotte'),
    ('Ça vole'),
    ('En l’air'),
    ('Chimique'),
    ('Chiffres et nombres'),
    ('Un ustensile'),
    ('Un outil'),
    ('Un aliment'),
    ('Voiture'),
    ('2 roues'),
    ('Vibration'),
    ('Troué'),
    ('Sur mon bureau'),
    ('Rayures'),
    ('Arbre'),
    ('Sur un fil'),
    ('Petite cuillère'),
    ('Sourire'),
    ('Tricolore'),
    ('Bicolore'),
    ('Duo'),
    ('Bris et débris'),
    ('Contraste'),
    ('Géométrie'),
    ('Lettres'),
    ('Zombie'),
    ('Superstition'),
    ('Construction'),
    ('Statue'),
    ('Fumée');
