INSERT INTO avatar
    (avatar_url)
VALUES
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/draw_pencil_addicted_love-512.png'),
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/cactus_cacti_avatar_pirate-512.png'),
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/sloth_lazybones_sluggard_avatar-512.png'),
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/indian_man_male_person-512.png'),
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/marilyn_monroe_artist_avatar-512.png'),
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/hipster_beard_male_man-512.png'),
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/bear_russian_animal_avatar-512.png'),
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/man_male_avatar_portrait-512.png'),
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/boy_afro_kid_child-512.png'),
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/builder_worker_helmet-512.png'),
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/girl_avatar_child_kid-512.png'),
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/zombie_avatar_monster_dead-512.png'),
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/grandma_elderly_nanny_avatar-512.png'),
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/chaplin_comedy_actor_man-512.png'),
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/boy_male_avatar_portrait-512.png'),
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/pilot_traveller_person_avatar-512.png'),
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/afro_woman_female_person-512.png'),
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/boy_person_avatar_kid-512.png'),
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/girl_female_woman_avatar-512.png'),
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/batman_hero_avatar_comics-512.png'),
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/ufo_alien_space_avatar-512.png'),
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/afro_avatar_male_man-512.png'),
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/girl_person_kid_child-512.png'),
    ('https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/female_woman_avatar_portrait-512.png');

INSERT INTO rule
    (rule_name)
VALUES
    ('Capture d\'écran'),
    ('Retouches'),
    ('Appareil photo'),
    ('Faire poser une personne'),
    ('Smartphone'),
    ('Ajout de texte'),
    ('Ajout d\'illustration');

INSERT INTO status
    (status_name)
VALUES
    ('post'),
    ('vote'),
    ('completed');

INSERT INTO theme
    (theme_name)
VALUES
    ('Encore un matin'),
    ('Vue d’en haut'),
    ('En-dessous'),
    ('Technologie'),
    ('Ras du sol'),
    ('Reflets'),
    ('Ombre'),
    ('Un objet'),
    ('Drapeaux'),
    ('Sublimer un déchets'),
    ('Amour'),
    ('Pays'),
    ('Vert'),
    ('Photo culinaire'),
    ('Bleu'),
    ('Rouge'),
    ('Jaune'),
    ('Noir'),
    ('Blanc'),
    ('Miroir'),
    ('Courbes'),
    ('Avant – après'),
    ('Symétrie'),
    ('Lignes'),
    ('Flower Power'),
    ('Petit bonheur'),
    ('Joie'),
    ('Peur'),
    ('Noir & Blanc'),
    ('Souvenir d’enfance'),
    ('Animal'),
    ('Dans mon sac'),
    ('Lecture'),
    ('Ecriture'),
    ('Coloré'),
    ('Escaliers'),
    ('Contre-jour'),
    ('Tic-Tac'),
    ('Horizon'),
    ('Caché'),
    ('Pont'),
    ('Ras du sol Reflets'),
    ('Vue du dessus'),
    ('Sur la tête'),
    ('C’est dans l’air'),
    ('Microcosmos'),
    ('Regard'),
    ('Yeux'),
    ('Mains'),
    ('Couteau'),
    ('Machine'),
    ('Pièce'),
    ('Clé'),
    ('Bijou'),
    ('Impossible'),
    ('Balle & ballon'),
    ('Rythme'),
    ('Sport'),
    ('Décalé'),
    ('Fourchette'),
    ('Fentes'),
    ('Œuf'),
    ('Pierre et rocher'),
    ('Nuit'),
    ('Métal'),
    ('Rue'),
    ('Répétition'),
    ('Feu'),
    ('Route'),
    ('Empilement'),
    ('Parallèle'),
    ('Perpendiculaire'),
    ('Opposés'),
    ('Champignon'),
    ('Argent'),
    ('Chaussure'),
    ('Silhouette'),
    ('Musique'),
    ('Multitude'),
    ('Mouvement'),
    ('Coucher de soleil'),
    ('Au bord de l’eau'),
    ('Petit trésor'),
    ('Splash !'),
    ('Surprise !'),
    ('Magie'),
    ('L’eau'),
    ('Porte'),
    ('A moitié'),
    ('Goutte'),
    ('Ne pas déranger'),
    ('Vieux'),
    ('Sale'),
    ('Illusion'),
    ('Propre'),
    ('Perspective'),
    ('De l’autre côté'),
    ('Fenêtre'),
    ('Liberté'),
    ('Lumière'),
    ('Temps'),
    ('Détail'),
    ('Solitude'),
    ('Absurde'),
    ('Vitesse'),
    ('Vagues'),
    ('Autoportrait'),
    ('Jeune'),
    ('Abandonné'),
    ('Froid'),
    ('Chaud'),
    ('Architecture'),
    ('Nature'),
    ('Texture'),
    ('Sombre'),
    ('Ailleurs'),
    ('Coupé'),
    ('Cinéma'),
    ('Guerre'),
    ('Horreur'),
    ('Paysage'),
    ('Gros plan'),
    ('Trio'),
    ('Nostalgie'),
    ('A la queue leu-leu'),
    ('Perché'),
    ('Rond(s)'),
    ('Carré(s)'),
    ('Ça flotte'),
    ('Ça vole'),
    ('En l’air'),
    ('Chimique'),
    ('Chiffres et nombres'),
    ('Un ustensile'),
    ('Un outil'),
    ('Un aliment'),
    ('Voiture'),
    ('2 roues'),
    ('Vibration'),
    ('Troué'),
    ('Sur mon bureau'),
    ('Rayures'),
    ('Arbre'),
    ('Sur un fil'),
    ('Petite cuillère'),
    ('Sourire'),
    ('Tricolore'),
    ('Bicolore'),
    ('Duo'),
    ('Bris et débris'),
    ('Contraste'),
    ('Géométrie'),
    ('Lettres'),
    ('Zombie'),
    ('Superstition'),
    ('Construction'),
    ('Statue'),
    ('Fumée');
