-- MySQL Script generated by MySQL Workbench
-- Sun Jul 12 20:54:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pix_battle
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pix_battle` DEFAULT CHARACTER SET utf8 ;
USE `pix_battle` ;

-- -----------------------------------------------------
-- Table `pix_battle`.`avatar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pix_battle`.`avatar` (
  `avatar_id` INT NOT NULL AUTO_INCREMENT,
  `avatar_url` VARCHAR(255) NULL DEFAULT '/src/asset/avatars/avatar_default.png',
  PRIMARY KEY (`avatar_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pix_battle`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pix_battle`.`status` (
  `status_id` INT NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(45) NOT NULL DEFAULT 'post',
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pix_battle`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pix_battle`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  `create_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `avatar_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_avatar`
    FOREIGN KEY (`avatar_id`)
    REFERENCES `pix_battle`.`avatar` (`avatar_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `email_UNIQUE` ON `pix_battle`.`user` (`email` ASC) VISIBLE;

CREATE INDEX `fk_user_avatar_idx` ON `pix_battle`.`user` (`avatar_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pix_battle`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pix_battle`.`group` (
  `group_id` INT NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(45) NULL DEFAULT NULL,
  `create_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `admin_user_id` INT NOT NULL,
  PRIMARY KEY (`group_id`),
  CONSTRAINT `fk_group_user1`
    FOREIGN KEY (`admin_user_id`)
    REFERENCES `pix_battle`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_group_user1_idx` ON `pix_battle`.`group` (`admin_user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pix_battle`.`theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pix_battle`.`theme` (
  `theme_id` INT NOT NULL AUTO_INCREMENT,
  `theme_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`theme_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 159
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pix_battle`.`battle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pix_battle`.`battle` (
  `battle_id` INT NOT NULL AUTO_INCREMENT,
  `deadline` DATETIME NULL DEFAULT NULL,
  `create_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `group_id` INT NOT NULL,
  `theme_id` INT NOT NULL,
  `admin_user_id` INT NOT NULL,
  `winner_user_id` INT NULL DEFAULT NULL,
  `status_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`battle_id`),
  CONSTRAINT `fk_battle_battle_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `pix_battle`.`status` (`status_id`),
  CONSTRAINT `fk_battle_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `pix_battle`.`group` (`group_id`),
  CONSTRAINT `fk_battle_theme1`
    FOREIGN KEY (`theme_id`)
    REFERENCES `pix_battle`.`theme` (`theme_id`),
  CONSTRAINT `fk_battle_user1`
    FOREIGN KEY (`admin_user_id`)
    REFERENCES `pix_battle`.`user` (`user_id`),
  CONSTRAINT `fk_battle_user2`
    FOREIGN KEY (`winner_user_id`)
    REFERENCES `pix_battle`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_battle_theme1_idx` ON `pix_battle`.`battle` (`theme_id` ASC) VISIBLE;

CREATE INDEX `fk_battle_group1_idx` ON `pix_battle`.`battle` (`group_id` ASC) VISIBLE;

CREATE INDEX `fk_battle_user1_idx` ON `pix_battle`.`battle` (`admin_user_id` ASC) VISIBLE;

CREATE INDEX `fk_battle_user2_idx` ON `pix_battle`.`battle` (`winner_user_id` ASC) VISIBLE;

CREATE INDEX `fk_battle_battle_status1_idx` ON `pix_battle`.`battle` (`status_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pix_battle`.`rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pix_battle`.`rule` (
  `rule_id` INT NOT NULL AUTO_INCREMENT,
  `rule_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rule_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pix_battle`.`battle_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pix_battle`.`battle_rule` (
  `battle_id` INT NOT NULL,
  `rule_id` INT NOT NULL,
  PRIMARY KEY (`battle_id`, `rule_id`),
  CONSTRAINT `fk_battle_has_rule_battle1`
    FOREIGN KEY (`battle_id`)
    REFERENCES `pix_battle`.`battle` (`battle_id`),
  CONSTRAINT `fk_battle_has_rule_rule1`
    FOREIGN KEY (`rule_id`)
    REFERENCES `pix_battle`.`rule` (`rule_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_battle_has_rule_rule1_idx` ON `pix_battle`.`battle_rule` (`rule_id` ASC) VISIBLE;

CREATE INDEX `fk_battle_has_rule_battle1_idx` ON `pix_battle`.`battle_rule` (`battle_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pix_battle`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pix_battle`.`photo` (
  `photo_id` INT NOT NULL AUTO_INCREMENT,
  `photo_url` VARCHAR(255) NOT NULL,
  `create_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `score` INT NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  `battle_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`photo_id`),
  CONSTRAINT `fk_photo_battle1`
    FOREIGN KEY (`battle_id`)
    REFERENCES `pix_battle`.`battle` (`battle_id`),
  CONSTRAINT `fk_photo_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `pix_battle`.`group` (`group_id`),
  CONSTRAINT `fk_photo_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `pix_battle`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_photo_user1_idx` ON `pix_battle`.`photo` (`user_id` ASC) VISIBLE;

CREATE INDEX `fk_photo_battle1_idx` ON `pix_battle`.`photo` (`battle_id` ASC) VISIBLE;

CREATE INDEX `fk_photo_group1_idx` ON `pix_battle`.`photo` (`group_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pix_battle`.`user_battle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pix_battle`.`user_battle` (
  `user_id` INT NOT NULL,
  `battle_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `battle_id`),
  CONSTRAINT `fk_user_has_battle_battle1`
    FOREIGN KEY (`battle_id`)
    REFERENCES `pix_battle`.`battle` (`battle_id`),
  CONSTRAINT `fk_user_has_battle_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `pix_battle`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_user_has_battle_battle1_idx` ON `pix_battle`.`user_battle` (`battle_id` ASC) VISIBLE;

CREATE INDEX `fk_user_has_battle_user1_idx` ON `pix_battle`.`user_battle` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pix_battle`.`user_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pix_battle`.`user_group` (
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `group_id`),
  CONSTRAINT `fk_user_has_group_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `pix_battle`.`group` (`group_id`),
  CONSTRAINT `fk_user_has_group_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `pix_battle`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_user_has_group_group1_idx` ON `pix_battle`.`user_group` (`group_id` ASC) VISIBLE;

CREATE INDEX `fk_user_has_group_user1_idx` ON `pix_battle`.`user_group` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pix_battle`.`user_photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pix_battle`.`user_photo` (
  `user_id` INT NOT NULL,
  `photo_id` INT NOT NULL,
  `vote` INT NOT NULL,
  `create_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `photo_id`),
  CONSTRAINT `fk_user_has_photo_photo1`
    FOREIGN KEY (`photo_id`)
    REFERENCES `pix_battle`.`photo` (`photo_id`),
  CONSTRAINT `fk_user_has_photo_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `pix_battle`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_user_has_photo_photo1_idx` ON `pix_battle`.`user_photo` (`photo_id` ASC) VISIBLE;

CREATE INDEX `fk_user_has_photo_user1_idx` ON `pix_battle`.`user_photo` (`user_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
